version: '3.8'

services:
  www:
    container_name: apache-php
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
    networks:
      - mynetwork
  db:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql-db
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: dportenis
      MYSQL_ROOT_HOST: '%'  # Permite conexiones de cualquier host
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: test
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
volumes:
  db-data: # Volumen para los datos de la base de datos
    driver: local